# Generated by Django 3.0.2 on 2020-09-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200905_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no-image.jpg', upload_to=''),
        ),
    ]
